namespace UltimaXNA.Ultima.Input
{
    public enum MacroType : int
    {
        None,
        UseSkill,
        CastSpell,
        OpenGump,
        CloseGump,
        Move,
        ArmDisarm,
        Say,
        Emote,
        Whisper,
        Yell,
        ToggleWarPeace,
        Paste,
        MinimizeWindow,
        MaximizeWindow,
        EmoteBow,
        EmoteSalute,
        QuitGame,
        ShowAllNames,
        LastTarget,
        TargetSelf,
        WaitForTarget,
        NextTarget,
        Delay,
        CloseAllGumps,
        SetAlwaysRun
    }
}
